spring.application.name=presupuesto
server.port=8080


spring.datasource.url=jdbc:mariadb://localhost:3306/presupuesto
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Permite que Hibernate cree / actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.rest.default-media-type=application/json

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
